### ISSUE TITLE
Languages: Translation strings pulled into project database

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#101]
Log into the workflow as an MC
Go to uploader
Change language to something else (choose Chinese)
Go to a project database page, such as https://librivox.org/add_catalog_item/152

Several of the items are now in Chinese:
- Is this a compilation? label
- Project language label
- Project type pick list
- Author labels
- Translator labels

@kgroeneveld

**Comment by kgroeneveld** [comment]
I have noticed the same thing before as well. I think it has been like this for a long time.

**Comment by redrun45** [comment]
Right, I can see the translation strings in the code. It looks like the whole Workflow application is designed with multiple languages, though the Project Screen doesn't have a language selector. It just remembers your language from the template generator or uploader.

I think we can close this issue - and if we want a language selector in more places, we can open a new one.
