### ISSUE TITLE
Errors in SOME compilation project catalog pages

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#109]
This project has errors in the author field:
https://librivox.org/worldstory-volume-xiv-outline-of-universal-history-by-karl-ploetz/

But the other compilations I'm looking at do not:
https://librivox.org/coffee-break-collection-30-mythical-creatures-by-various/

The one with the error (1) has over 100 sections; (2) does not have cover art yet. It's a new project, cataloged yesterday. Those are the only differences I've come up with, and it would be strange to have them be the cause!

**Comment by twinkietoes-on** [comment]
Aha! It seems to only occur on compilations where the author is unassigned. I cannot think of a project where this occurs except in error. (This specific project, I think, shouldn't be a compilation.)

**Comment by notartom** [comment]
So the fix would be to set the correct project type on those authorless compilations (that aren't actually complication?)

**Comment by twinkietoes-on** [comment]
I don't know. I have to think this through a bit more. I think in this case it's user error (no authors + no text in the sections =  not a compilation). But I am trying to remember if there are cases where it's a compilation with separate texts but no author in the sections. Example would be a single author project with multiple texts, which may not have the author put in the sections.

Definitely no author + no text = not a compilation, but not sure about just no author.

**Comment by notartom** [comment]
Well, I've haxxed some `isset`s on the live server (I know, not great, but our staging database snapshot is out of date and doesn't have that project to test with) to at least just show the empty string (and not the PHP error). This is obviously temporary.

**Comment by kgroeneveld** [comment]
>Well, I've haxxed some issets on the live server (I know, not great, but our staging database snapshot is out of date and doesn't have that project to test with) to at least just show the empty string (and not the PHP error). This is obviously temporary.

I submitted a pull request before your post that adds an `isset`. I tested it by creating a compilation on my test server with a section with no author.  Whether this should be considered a valid project and allowed to be created is another question, but adding a check for null author in `format_author` seems reasonable in any case.

**Comment by notartom** [comment]
Fixed by PR#110
