### ISSUE TITLE
Speed up catalog search by reader

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#127]
A member wrote: "I've noticed that any search of the Librivox catalogue by reader is very, very slow. I'm wondering if the speed of this search could be improved by an expedient as simple to implement as creating a database level index on the relevant reader field(s)?"

Priority: 3 (Medium)

**Comment by ITD88** [comment]
Could someone who has a working version of the test database try profiling

**Comment by twinkietoes-on** [comment]
Apparently the software updates vastly improved this. We can probably close the issue and reopen it in the future if we discover it has slowed down again. (I'd close it, but I'm not sure which option to choose.)

**Comment by notartom** [comment]
Huh, I knew the new versions of MySQL and PHP were supposed to be faster, but I didn't expect it to be this... obvious?
