### ISSUE TITLE
Since CI3 we are not being logged out of the workflow until cookies are cleared

### ISSUE THREAD

**Issue by notartom** [LibriVox/librivox-catalog#143]
Since this change (I think, or shortly thereafter with one of the subsequent changes), we are not being logged out of the workflow until cookies are cleared. Is this a security issue that we would want to address, or is it okay?
(EDIT to add: I accept cookies until I close my browser, so I'm not logged out unless I do that, which can be days or more where the workflow is accessible on my computer.)

_Originally posted by @twinkietoes-on in https://github.com/LibriVox/librivox-catalog/issues/7#issuecomment-824923478_

**Comment by twinkietoes-on** [comment]
Oh, we're definitely being logged out of the workflow now. I don't know the time limit, but it's somewhere between 10 and 20 minutes (and drives me crazy every time I get caught in a logged out screen). LOL

**Comment by redrun45** [comment]
Workflow keeps us logged in as it ought to now, so I think we can close this issue.

I'm looking around to see where I might most helpfully dig in.  With any luck, I'll find another few issues already fixed, as I look around.  :)
