### ISSUE TITLE
Converting Google Sheet issues to GitHub Issues

### ISSUE THREAD

**Issue by RayBB** [LibriVox/librivox-catalog#15]
Hey there,

I saw your request on [here](https://news.ycombinator.com/item?id=23563956) HN for some help.

In this contributing document [here](https://github.com/LibriVox/librivox-catalog/commit/8772747219efc02c0843de9d76e0245afc431241?short_path=6a33714#diff-6a3371457528722a734f3c51d9238c13) you mentioned the first task being to move issues from [this](https://docs.google.com/spreadsheets/d/1LTMEmwxH1vKLwNXN4U3wop69ElWFjnmqWyV5Jxbl9qc/edit#gid=0) google sheet into github.

Seeing as it's only ~70 issues I'd be willing to help by pulling them in if that's helpful. I don't know anything about PHP or CodeIgniter so my context is limited but if this makes it easier for others to get involved I'm willing to do it!

I have a few questions:
1. Will you, or someone, actually find it useful to move all those issues from Google sheets into github or maybe is it better rto start fresh?
2. Is the Google Sheet up to date (as in, are most issues still valid)? If not, deleting the invalid ones would save us all some time.
3. I'm willing to do this manually and try to tag things as feature enhancement/bug or whatever else. Is that something you'd like?
4. Is there anything else we should figure out before I start moving them over?

Thanks so much for all the hard work volunteers put into this project. Let me know what I can do to best help 👍

**Comment by eXpl0it3r** [comment]
I've been having a look at the sheet and it's sometimes a bit hard to figure out that state of a listed issue. It reads to me like the first three have already been completed. Missing link to that email for issue 4 and 5 I'm unsure whether this indicates that it was fixed or that it needs verification. I guess it might be a good idea to search the forum for the original posts, maybe some of the issues make more sense then and maybe there's also some information on the status.

If I can help you out, let me know, other than that, I'll first have to familiarize myself a bit more with LibriVox itself to understand certain descriptions.

**Comment by RayBB** [comment]
@eXpl0it3r I just registered for account on the forum. It looks like they do manual verification so I recommend registering soon as you can.

It's a good idea to try to track down some issues in the forum and see if they were resolved. I'll start poking around once my account is activated.

I also think it may be good to add some issue templates similar to the ones [here](https://github.com/LemmyNet/lemmy/issues/881).

**Comment by RayBB** [comment]
@eXpl0it3r there's some discussion going on here: https://forum.librivox.org/viewtopic.php?f=17&t=81235

**Comment by notartom** [comment]
I think the tech stuff should remain here as much as possible. The forums are for the "real" volunteer readers and organisers. There are a few volunteer admins (volunteers who do more than just read books - they organise, moderate, plan, etc) that I liaise with for all things tech, so we should figure out the best way to communicate with them (until now I was alone, so email was enough). There's a "Tech" section in the admin subforums, maybe that could be the place.

**Comment by twinkietoes-on** [comment]
TriciaG from LibriVox here. I've done a little addition to and updating of that Google Sheet. It has a new link with my changes: [https://docs.google.com/spreadsheets/d/1wiRaSZnR7m8I2bc2RjV1G9XpNOVMurAZOYnNjLOnooc/edit#gid=0](url)
It's not even close to perfect, by any means.

**Comment by twinkietoes-on** [comment]
I've made GitHub issues of some of the higher priority issues on the Google Sheet page. If they look acceptable, I can continue to enter more of them.

**Comment by RayBB** [comment]
looks like a great start! @twinkietoes-on

**Comment by twinkietoes-on** [comment]
I've entered all the issues from the spreadsheet that are (ahem) worthy. Any left out must be discussed among the LibriVox admins to determine if/how we want them done. So this issue may be closed.

**Comment by notartom** [comment]
"Only" 47 open issues left ;)

Much thanks @twinkietoes-on, let's close this.
