### ISSUE TITLE
Reader page access ignores query string

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#158]
(I hope this is clear enough. It's just beyond my thorough understanding. I'm copy/pasting.)

Any access to the reader page (eg, https://librivox.org/reader/8463) clobbers the querystring.
For example:
https://librivox.org/reader/8463?primary_key=8463&search_category=reader&search_page=4&search_form=get_results

The query includes the parameter "search_page=4", so the expected behavior would be to display results starting on page 4. Instead the search script ignores the entire querystring and displays the first page of results.

https://forum.librivox.org/viewtopic.php?p=2156227#p2156227

**Comment by redrun45** [comment]
Thanks to garethsime (thank you!), we no longer lose the page on reader searches.  We might close this as fixed, since I don't see anything else there to be broken by the clobbering.

**Comment by notartom** [comment]
So as @garethsime said in https://github.com/LibriVox/librivox-catalog/pull/167, his patch fixes Author, Group, and Reader pages. Are there other pages where the query string is being ignored that haven't been fixed by his patch?

**Comment by redrun45** [comment]
Not that I'm aware of.  I think if we run into any more such issues, we can file them separately.
