### ISSUE TITLE
Dramatic Works Template - missing end of book statement

### ISSUE THREAD

**Issue by notartom** [LibriVox/librivox-catalog#17]
Copied verbatim from: https://forum.librivox.org/viewtopic.php?f=49&t=79828 (forum admin permissions are necessary).

application/views/public/project_launch/dramatic_work.php

Please add the following code to the Dramatic Works Template

[*]<?= lang('project_launch_template_end_of_book')?>
<?= sprintf(lang('project_launch_template_end_of_title'),$title, $author[0], $translator_all )?> [/list]

after this code (line 114 on Github)
<?= lang('project_launch_template_drama_at_end_of_act')?> <?= sprintf(lang('lang_key'), $title,$author[0], $translator_all )?>

This is and example of what the code create:

At the end of the book, say (in addition):
"End of The Chimney Corner, by Harriet Beecher Stowe. "

**Comment by kgroeneveld** [comment]
This issue is being addressed in PR #23.

**Comment by twinkietoes-on** [comment]
This issue may be closed, as it was in PR 23 merged yesterday.
