### ISSUE TITLE
Uploader Not Accepting FLAC Files

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#171]
Our uploader at https://librivox.org/uploader used to accept FLAC files. It appears to no longer accept them, returning an error:

_undefined NaN KB Error The filetype you are attempting to upload is not allowed._

This was first noticed end of December; I don't know if it was a problem earlier than that. It is just verified with at least 2 people, one exporting using Audacity and one using Sony Sound Forge.

**Comment by hamidsafdari** [comment]
I tested the following files I found online and their MIME is set to `audio/flac` but the app only accepts `audio/x-flac`. Made that an array in `application/config/mimes.php` with the value `array('audio/x-flac', 'audio/flac')`.

![screenshot_2023-11-16_21-53_1](https://github.com/LibriVox/librivox-catalog/assets/5158006/65cb1527-5b74-4f9a-b8f4-601fcb73c3cf)
![screenshot_2023-11-16_21-54](https://github.com/LibriVox/librivox-catalog/assets/5158006/bc7d7009-8250-47e8-a8e4-0f685560e3fd)
![screenshot_2023-11-16_21-54_1](https://github.com/LibriVox/librivox-catalog/assets/5158006/233e1f34-3e55-4444-a8d8-681dff27bd3e)

**Comment by hamidsafdari** [comment]
I also found that some .mp3 files have a MIME type of `application/octet-stream`. The following patch fixes the issue (found on stackoverflow :grin: ) but I didn't include that in my pull request since `application/octet-stream` applies to a wide range of files. Waiting for someone's input on this.

```diff
diff --git a/application/libraries/MY_Upload.php b/application/libraries/MY_Upload.php
--- a/application/libraries/MY_Upload.php	(revision 9a742739aa3125233631854de5a35d9f8591f650)
+++ b/application/libraries/MY_Upload.php	(date 1700154035842)
@@ -46,4 +46,19 @@
 		return rename($path.$original, $path.$new_filename);
 	}
 
+	/**
+	 * Override application/octet-stream on file_type
+	 *
+	 * @param array $file
+	 * @return   void
+	 */
+	protected function _file_mime_type($file)
+	{
+		parent::_file_mime_type($file);
+
+		if ($this->file_type == 'application/octet-stream' && !empty($file['type']))
+		{
+			$this->file_type = $file['type'];
+		}
+	}
 }
\ No newline at end of file
```

**Comment by notartom** [comment]
> I also found that some .mp3 files have a MIME type of `application/octet-stream`. The following patch fixes the issue (found on stackoverflow 😁 ) but I didn't include that in my pull request since `application/octet-stream` applies to a wide range of files. Waiting for someone's input on this.

It's a good instinct to be weary of those files :) I think until someone reports it as being a problem, we can stick to solving the FLAC issue (which you have, thanks!).
