### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [LibriVox/librivox-catalog#172]
Please add a license (ie MIT/ISC/BSD/etc)

**Comment by fakerybakery** [comment]
@notartom is this completed? Your commit is in a separate fork, not the main repository. Is this going to be merged?

**Comment by notartom** [comment]
*sigh* I accidentally pushed this to my own fork instead of the main repo, didn't? Fixed now.

PS: This, among many other reasons, is why Gerrit is objectively better, and no one's going to convince me of the contrary.

**Comment by fakerybakery** [comment]
Thank you!!

**Comment by fakerybakery** [comment]
Hi @notartom, one thing: the LibriVox website has a "0 - Public Domain" badge on the bottom of the website. This might be confusing as the code itself is not in the public domain, but only the audiobooks. Are you planning to add a notice that the audiobooks are in the public domain but not the code? Thank you!

**Comment by notartom** [comment]
Faut point. Do you mean a notice on the website itself, or somewhere here in the repo?

**Comment by fakerybakery** [comment]
Hi,
It's on the librivox.org website in the footer (at the very bottom of the webpage). [Here](https://github.com/LibriVox/librivox-catalog/blob/master/application/views/catalog/partials/footer.php#L7)'s where it's defined in the code.

![Screenshot](https://github.com/LibriVox/librivox-catalog/assets/76186054/343cfccd-fea4-49f3-9a09-787468c97157)


Thank you for considering!

**Comment by notartom** [comment]
Right, sorry, I should have been more clear: where do you imagine the notice about the code being MIT instead of public domain? Here somewhere, or on the web page?

**Comment by fakerybakery** [comment]
Hmm... I don't know. I guess its probably clear enough that "0 Public Domain" refers to the audio files. Sorry about the trouble. Thanks!
