### ISSUE TITLE
Be able to narrow down the author choice in Template Generator

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#197]
https://librivox.org/add_project

When typing in a common surname for the author, or one that is a partial match to a lot of other names, it returns a long list. Example: typing in "Smith" gives you "Grossmith" and every other surname that contains "Smith" somewhere in it, and the list is getting unwieldy. There's no way to narrow it down (for example, you can't type the first/given name to narrow the list).

I don't know the best solution, but we do need a way to narrow down this list for people to find the author to select; otherwise, they'll give up and make a duplicate author.

**Comment by peterjdann** [comment]
Seems to me the behaviour we see here would be better if:

- In a case where the user has specified only an author surname, the results were sorted by first name. This would mean that "Andrew Smith" would be listed in the dropdown before "Austin Smith" (I made up these examples)
- In a case where the user has specified only an author first name, the results were sorted by author surname. This would mean that "Mary Bolton" was listed before "Mary Boulton" (again, I made this up)

This change would be pretty easy to implement, and while it wouldn't completely solve the OP's problem, it might go some way to allleviating the pain.

**Comment by peterjdann** [comment]
Sorry it's taken me a few days to get to look at this properly. I think the way you've tackled this is far better than my own version. I don't see any value in presenting both options at all.

What is the best way for us to proceed now to get your change implemented? I'd be perfectly happy to have my own pull request aborted/cancelled/deleted (not quite sure how this works) if the easiest way to get this done would be for you to raise a fresh pull request that implements the change whose effects you've illustrated above.

**Comment by peterjdann** [comment]
> Honestly, having two options is good in any case! If you'd like to cancel #232 for now, I have no objections, but we'll at least still have the screenshots. I'll see what other admins think about them, and then I can put up either version (with added pseudonym fix) for technical review. 👍

I've closed #232. I think you solution is much better!
