### ISSUE TITLE
Make Archive links in the Database https

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#26]
Currently the catalog system generates the Archive link and Zip link as http. It needs to be https to prevent "mixed security content" type warnings. 
Also, retroactively fix the links in the current catalog entries.

See this post and following for an instance of a user not being able to access the ZIP file: https://forum.librivox.org/viewtopic.php?p=1829519#p1829519

Priority: 1

**Comment by twinkietoes-on** [comment]
It appears the Archive page in the database is still not generating as https.

And as a side note, the *.mp3 links to Archive on old catalog pages are still http. Example: https://librivox.org/eusebius-history-of-the-christian-church-tr-by-mcgiffert/
where all the audio links (the > play icon and the section title, those are the two bitrate files) are http.

**Comment by notartom** [comment]
> It appears the Archive page in the database is still not generating as https.

I can't actually find anywhere in the code where a hardcoded `http://` would be doing this. Can you give an example of how I can reproduce/observe this?

> And as a side note, the *.mp3 links to Archive on old catalog pages are still http. Example: https://librivox.org/eusebius-history-of-the-christian-church-tr-by-mcgiffert/ where all the audio links (the > play icon and the section title, those are the two bitrate files) are http.

**Comment by twinkietoes-on** [comment]
It happens in the cataloging process. When in the Validator, a project is sent to Archive. In that process, the slug for the Zip and Archive page are generated, as well as the file duration and Zip file size, all of which are added to the database entry.

The Archive URL is still generating as http. Here in the live site is a recent example, cataloged today: https://librivox.org/add_catalog_item/16077

**Comment by notartom** [comment]
> The Archive URL is still generating as http. Here in the live site is a recent example, cataloged today: https://librivox.org/add_catalog_item/16077

When I click that I get correct https:// links - I'm assuming because they've been manually fixed? I'm afraid I'll need a step-by-step walkthrough to understand where the http:// is initially coming form.

**Comment by twinkietoes-on** [comment]
Err, it is http. See image.


    On Sunday, November 14, 2021, 11:07:05 a.m. EST, Artom Lifshitz ***@***.***> wrote:  
 
 



The Archive URL is still generating as http. Here in the live site is a recent example, cataloged today: https://librivox.org/add_catalog_item/16077


When I click that I get correct https:// links - I'm assuming because they've been manually fixed? I'm afraid I'll need a step-by-step walkthrough to understand where the http:// is initially coming form.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by notartom** [comment]
Oh, just saw it, sorry. So that's actually a value in a config file, so I fixed it with https://github.com/LibriVox/librivox-ansible/commit/06aeaf38f69d6d71b27170600f1a70a70fc99c5a in the librivox-ansible project.

**Comment by notartom** [comment]
> And as a side note, the *.mp3 links to Archive on old catalog pages are still http. Example: https://librivox.org/eusebius-history-of-the-christian-church-tr-by-mcgiffert/ where all the audio links (the > play icon and the section title, those are the two bitrate files) are http.

Btw, this has sorted with commit https://github.com/LibriVox/librivox-catalog/commit/71a9be1469fd215e3430e8268c38cd40f45079ef (and then running the script to update the database).
