### ISSUE TITLE
Files encoded to constant bitrate 128 kbps mp3 with LAME 3.100 show as 129 kbps instead of 128 kbps in the Validator

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#28]
"I downloaded the [new] version of LAME and associated it with my copy of Audacity. Then I downloaded a file by a different reader from your project that passes in the validator, reexported it with the new version of lame and then uploaded both into a validator page. The original shows as 128 and the one exported with LAME 3.100 is showing as 129."

Priority: 1

**Comment by kgroeneveld** [comment]
I have basically figured out what is causing this and have a fix. But I still want to do some more testing before I submit a PR.
