### ISSUE TITLE
Delay for Dropdown Lists is too short, sporadic

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#29]
Dropdown lists for readers and authors come up faster than average person can type in a few letters. Currently you have to click back in the entry field to continue typing to narrow down the list. 

Update: Since the latest upgrade of the database software, the dropdown lists aren't working as they should. List flashes but doesn't stay visible. It sometimes works, sometimes doesn't. Finicky!

Priority: 1

**Comment by kgroeneveld** [comment]
Note that the commit log mentioned above had a typo (which I now fixed) that referenced the wrong issue. That commit is not related to this issue.

**Comment by kgroeneveld** [comment]
I have been working on improving the auto complete drop down lists and should have a commit ready soon. Just thought I would mention it in the off chance someone else decides to work on it at the same time.

**Comment by twinkietoes-on** [comment]
This Issue has been resolved in a merge made this evening. I don't see the pull request for it to give more specifics.
