### ISSUE TITLE
Search result pagination improvement

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#32]
current pagination at bottom of results:
  « 1 2 3 4 5 » (even if there are 200 pages).
 
requested pagination interface is:
 « 1 2 3 4 5 ... 778 » (Go page X)
 
when you are in the middle of results:
 « 1 ... 77 78 79 80 81 ... 778 » (go to page X)
 
where ...
 a) 778 is the whatever the last page Is.
 b) go to page (X) ... the (X) is an inputtable number.
 
in the case that an X is entered that is greater than the last page, just go to the last page.
 

 but crap:
 lots of requests for alphabetical results...
 
 wonder: can we put this on the Advanced Search Page as an additional filter...?
 
  Starting with (alphabet dropdown). 

Priority: 2

**Comment by notartom** [comment]
I think we can close this now that https://github.com/LibriVox/librivox-catalog/pull/164 has landed?

**Comment by twinkietoes-on** [comment]
I think so. A definite improvement - thanks, garethsime!

**Comment by garethsime** [comment]
No worries 🙂 Notably though, the new work I've done doesn't include the 'Go to X' field. I'm not sure how far into the pagination people will want to go instead of doing another search though, so I don't know if it's worth doing

**Comment by twinkietoes-on** [comment]
And if they're at all web-savvy, they can see they could simply change the page number in the URL. Ha!
    On Saturday, April 22, 2023 at 04:03:30 p.m. EDT, Gareth Sime ***@***.***> wrote:  
 
 


No worries 🙂 Notably though, the new work I've done doesn't include the 'Go to X' field. I'm not sure how far into the pagination people will want to go instead of doing another search though, so I don't know if it's worth doing
