### ISSUE TITLE
Add confirmation for deleting rows in section compiler

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#35]
can a confirmation dialog box be added to ask for confirmation when deleting rows in the section compiler (similar to what happens in the Validator)?

Priority: 2

**Comment by redrun45** [comment]
On further discussion, having a confirmation every time would be too much friction for certain projects, where MCs often have to delete _a lot_ of sections at cataloging time.

Alternatively, we can hide the Delete buttons until another button at the top is clicked, to prevent most accidents.
A pair of options for what this could look like, shown here in the top right, along with the tooltip that would pop up when you hover over it:

Option A - just an 'X':
![delete_column_before](https://github.com/LibriVox/librivox-catalog/assets/115442035/1078cf9d-4165-4e5c-b6da-0331b4a29951)

Option B - more descriptive button text:
![delete_column_before_alt](https://github.com/LibriVox/librivox-catalog/assets/115442035/fafb3fb5-818a-4afe-984b-7e7cecc9b83b)



Clicking that button toggles the display of the whole column of Delete buttons:
![delete_column_after](https://github.com/LibriVox/librivox-catalog/assets/115442035/61329690-4d23-41ae-8d0f-234f21089850)

**Comment by redrun45** [comment]
Looks like the preferred option would be for a one-time pop-up (after confirming deletion one section, it would not ask again for the next ones), but we don't really have consensus that anything should change at all.

Closing this bug for now, but I'll save my WIP code in case we change our minds later.
