### ISSUE TITLE
Remove some vertical white space from the home page

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#38]
Quite a few people (including several of the experienced admins) don't realize that there is more to the home page than the Read and Listen boxes because that is all that shows when the page opens on some screens - so it isn't obvious that you should scroll down for more content. In particular folks don't realize that the new releases are lower down on this page.
 
It does seem like some of the vertical spacing could be removed so that a bit more of the lower part of the page was visible.
 
https://forum.librivox.org/viewtopic.php?p=939217#p939217 (post in the admin area)

Priority: 1-2

**Comment by redrun45** [comment]
Looks like this one would best be fixed from the Wordpress theme repository.  Closing and re-opening there.  :+1:
