### ISSUE TITLE
Limit suggested validator directory name

### ISSUE THREAD

**Issue by twinkietoes-on** [LibriVox/librivox-catalog#44]
Auto-generated Validator directory names that are too long do not get auto-deleted after cataloging. They're auto-generated using the project title. Shorten the suggested name somehow - truncate it after X characters?

Priority: 2

**Comment by redrun45** [comment]
One other note on this ticket: it's common practice to remove the underscore (_) characters that are suggested to separate words.  We can gain a little by removing those from the suggestion logic.
